name: ISSUE TEMPLATE
description: File a ISSUE TEMPLATE
title: '✨ Feat: '

body:
  - type: markdown
    attributes:
      value: |
        JDON 이슈 템플릿입니다! 
        ✨ 새로운 기능 추가 및 기존 기능 요구사항에 맞춰 수정
        🐛 기능에 대한 버그 수정
        📦 패키지 매니저 수정, 그 외 기타 수정
        ♻️ 코드 리팩토링
        💄 CSS 및 디자인 수정
        📝 문서 수정
        🧪 테스트 코드 관련
        👨‍⚕️ QA 관련 내용 작성
        🚨 Hotfix, 급한 수정

  - type: textarea
    id: title
    attributes:
      label: ✨ 작업 내용
      description: 해야할 작업에 대해서 간단하게 적어주세요
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: ⚙ 상세한 작업 내용
      description: 상세한 작업 내용을 적어주세요
      value: '- [ ] :

        - [ ] :

        - [ ] : '
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: 🛠 예상 소요시간
      multiple: false
      options:
        - 하루 이상
        - 12시간 이내
        - 5시간 이내
        - 3시간 이내
        - 1시간 이내
        - 30분 이내
