name: Build React App
on:
  push:
    branches:
      - develop
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: .env setting
        run: |


          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            touch .env
            echo "REACT_APP_API_ENDPOINT=${{ secrets.REACT_APP_API_DEV_ENDPOINT }}" > .env
            cat .env
          elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
            touch .env
            echo "REACT_APP_API_ENDPOINT=${{ secrets.REACT_APP_API_ENDPOINT }}" > .env
            cat .env
          fi
        shell: bash
      - name: Npm Install
        run: |
          npm install
      - name: Npm Build
        run: |
          npm run build
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          REACT_APP_API_ENDPOINT: ${{ github.ref == 'refs/heads/develop' && secrets.REACT_APP_API_DEV_ENDPOINT || secrets.REACT_APP_API_ENDPOINT }}
          AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: 'build'
